healthnet/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    #message system
    url(r'^messages/', include('postman.urls')),

    # url(r'^blog/', include('blog.urls')),
    url(r'^index', 'healthnet.views.index', name='index'),
    
    url(r'^admin/', include(admin.site.urls), name='admin-site'),
    #users
    url(r'^users/', include('users.urls')),
    #
    url(r'^account/', include('accounts.urls')),
    url(r'^medicalinfomation/', include('medicalinfo.urls'), name='med-info'),

    
    url(r'^contactus/$', 'healthnet.views.contactus', name='contactus'),
    url(r'^statistic/$', 'healthnet.views.statistic', name='statistic-home'),

	url(r'^$', 'healthnet.views.home', name='home'),

)

handler403 = 'healthnet.views.http403'
handler404 = 'healthnet.views.http404'

medicalinfo/urls.py
from django.conf.urls import patterns, url
from medicalinfo import views

urlpatterns = patterns('',
	url(r'^$', views.index),
	#url(r'^register/$', views.patient_register, name='patient-register'),

	url(r'^(?P<ref_id>[\w]+)/initializing/$', views.medinfo_init,name='med-info-init'),
	url(r'^(?P<ref_id>[\w]+)/new-case/$', views.case_init,name='case-init'),
	url(r'^(?P<ref_id>[\w]+)/cases/(?P<case_id>[\d]+)/new-prescription/$', views.case_update_prescription,name='case-update-prescription'),
	url(r'^(?P<ref_id>[\w]+)/cases/(?P<case_id>[\d]+)/update/$', views.case_update,name='case-update'),

	url(r'^(?P<ref_id>[\w]+)/cases/(?P<case_id>[\d]+)$', views.case_detail_view,name='case-detail-view'),

	url(r'^(?P<ref_id>[\w]+)/cases/$', views.case_list_view,name='case-list-view'),

	
	#url(r'^(?P<ref_id>[\w]+)/new-case/$', views.diagnosis_init,name='case-init'),


	url(r'^(?P<ref_id>[\w]+)/$', views.medinfo_view,name='med-info-detail'),
	#url(r'^(?P<ref_id>[\w]+)/update/$', views.userprofile_update, name='userprofile-update'),

)

users/urls.py
from django.conf.urls import patterns, url
from users import views 
urlpatterns = patterns('',
	url(r'^$', views.index),

)

medicalinfo/models.py
from django.db import models
from users.models import Patient, Doctor, Nurse, UserProfile
from django.contrib.auth.models import User
from localflavor.us.models import USStateField, USZipCodeField, USSocialSecurityNumberField, PhoneNumberField
from django.core.urlresolvers import reverse
#to track model 
from simple_history.models import HistoricalRecords

#to exclude custom fields when migrate with sould
#from south.modelsinspector import add_introspection_rules
#add_introspection_rules([], ["^localflavor\.us\.models"])


# Create your models here.


class MedicalInformation(models.Model):
	#history = HistoricalRecords()
	patient = models.OneToOneField(Patient, primary_key=True, verbose_name='Patient')
	#primary_doc = models.ForeignKey(Doctor, verbose_name='Primary Doctor', null=True)

	initialized = models.BooleanField(default=False)
	fName = models.CharField(max_length=40, verbose_name ="First Name")
	lName = models.CharField(max_length=40, verbose_name ="Last Name",)
	mName = models.CharField(max_length=40, verbose_name ="Middle Name", blank=True )

	#problem = models.CharField(max_length=200, verbose_name="Your concerns/problems")
	#dOB = models.DateField(null=True)
	#current_problem = models.CharField(max_length=200, blank=True)



	class Meta:
		permissions = (
			("init_medinfo", "can initialize med-info"),
			("read_medinfo", "can view med-info"),
			("init_case", "can init diagnosis"),
		)

	@classmethod
	def create(info, patient):
		new_info = info(patient=patient)
		return new_info
	def __str__(self):
		return self.patient.patient.username

class ChronicMedicalProblems(models.Model):
	#history = HistoricalRecords()
	medinfo = models.OneToOneField(MedicalInformation, verbose_name="Med-info", primary_key=True)
	high_blood = models.BooleanField(default=False, verbose_name="High Blood Pressure")
	heart = models.BooleanField(default=False, verbose_name="Heart Disease")
	diabete = models.BooleanField(default=False, verbose_name="Diabetes")
	stroke = models.BooleanField(default=False, verbose_name="Stroke")
	cancer = models.BooleanField(default=False, verbose_name="Cancer")
	thyroid = models.BooleanField(default=False, verbose_name="Thyroid")
	asthma = models.BooleanField(default=False, verbose_name="Asthma")
	other = models.CharField(max_length=200, blank=True, verbose_name="Others")

	def __str__(self):
		return self.medinfo.patient.patient.username

class Allergen(models.Model):
	medinfo = models.OneToOneField(MedicalInformation, verbose_name="Med-info", primary_key=True)
	food = models.BooleanField(default=False, verbose_name="Food Allergic")
	food_allegies = models.CharField(max_length=200, blank=True, verbose_name="Food")
	drug = models.BooleanField(default=False, verbose_name="Drug Allergic")
	drug_allegies = models.CharField(max_length=200, blank=True, verbose_name="Drugs")
	environmental = models.BooleanField(default=False, verbose_name="Environmental Allergic")
	environmental_allegies = models.CharField(max_length=200, blank=True, verbose_name="Environment")

	def __str__(self):
		return self.medinfo.patient.patient.username


class EmergencyContact(models.Model):
	#history = HistoricalRecords
	patient = models.OneToOneField(Patient, primary_key=True)
	name = models.CharField(max_length=100, blank=True, verbose_name="Emergency Contact Name")
	phone = PhoneNumberField(blank=True, verbose_name="Phone")
	relationship = models.CharField(max_length=20, blank=True, verbose_name="relationship to patient")

	def __str__(self):
		return self.patient.patient.username


class InsuranceInformation(models.Model):
	INSURANCE_CHOICES = (
        ('B', 'Blue Choice Options'),
        ('U', 'United Healthcare'),
        ('M', 'Medicaid'),
        ('N', 'None'),
        )

	#history = HistoricalRecords()
	patient = models.OneToOneField(Patient, primary_key=True, verbose_name='Related Patient')
	policy_holder = models.CharField(max_length=100, verbose_name="Policy Holder", blank=True)
	carrier = models.CharField(max_length=1, verbose_name="Insurance Carrier", choices=INSURANCE_CHOICES, default='N')
	policy_number = models.CharField(max_length=10, verbose_name="Policy Number", blank=True)

	def __str__(self):
		return self.patient.patient.username

#
#When a patient have a problem, a case will be created and will be used by doctor to 
#diagnose, update test result, and prescription
#
class Case(models.Model):
	CASE_STATUS_CHOICES = (
        ('A', 'Active'),
        ('C', 'Closed'),
        ('N', 'New'),
        )
	LAST_ACTION_CHOIES = (
		('N', 'Created'),
		('D', 'Updated'),
		('P', 'New Prescription Updated'),
		)

	#history = HistoricalRecords()
	medinfo = models.ForeignKey(MedicalInformation, verbose_name="Med-info")
	status = models.CharField(max_length=1, choices=CASE_STATUS_CHOICES, verbose_name='Case Status', default='N')
	#patient = models.ForeignKey(Patient, verbose_name='Related Patient')
	problem = models.CharField(max_length=200, verbose_name='Problem/Concern')
	diagnosis = models.CharField(max_length=200, verbose_name='Diagnosis', default='None')
	test_result = models.CharField(max_length=200, verbose_name='Test Result', default='None')
	last_action = models.CharField(max_length=1, choices=LAST_ACTION_CHOIES, verbose_name='Last action', default='N')
	created = models.DateField(auto_now_add=True, auto_now=False)
	updated = models.DateTimeField(auto_now_add=False, auto_now=True)

	def __str__(self):
		return self.problem


		'''
	@classmethod
	def create(info, patient):
		new_info = info(patient=patient)
		return new_info'''

class Prescription(models.Model):
	#history = HistoricalRecords()
	case = models.ForeignKey(Case, verbose_name="Related Case")
	#doc = models.ForeignKey(Doctor, verbose_name="Doctor")
	drug = models.CharField(max_length=200, verbose_name="Drug")
	instruction = models. CharField(max_length=200, verbose_name="Instruction")
	refill = models.PositiveSmallIntegerField(default=0, verbose_name="Refill")
	created = models.DateField(auto_now_add=True, auto_now=False)
	updated = models.DateTimeField(auto_now_add=False, auto_now=True)

	def __str__(self):
		return self.case + " " + self.drug

medicalinfo/forms.py
from django import forms
from django.contrib.auth.models import User
from users.models import UserProfile, Patient, Employee
from django.forms.models import model_to_dict, fields_for_model
from django.utils.translation import ugettext, ugettext_lazy as _


from localflavor.us.forms import USSocialSecurityNumberField, USPhoneNumberField

from medicalinfo.models import (MedicalInformation, ChronicMedicalProblems, 
    EmergencyContact, InsuranceInformation, Allergen, Case, Prescription,
)


class ChronicMedicalProblemsForm(forms.ModelForm):

    class Meta:
        model = ChronicMedicalProblems
        exclude = ['medinfo']

class MedinfoInitForm(forms.ModelForm):
    error_css_class = 'form-group has-error'

    class Meta:
        model = MedicalInformation
        exclude = ['patient', 'initialized']
        widgets = {
            'fName' : forms.TextInput(attrs={'class':'form-control '}),
            'lName' : forms.TextInput(attrs={'class':'form-control'}),
            'mName' : forms.TextInput(attrs={'class':'form-control'}),
        }
class CaseInitForm(forms.ModelForm):

    class Meta:
        model = Case
        exclude = ['medinfo','status','diagnosis','test_result','last_action']
        widgets = {
            'problem' : forms.Textarea(attrs={'class':'form-control', 'rows':6}),
        }

class CaseForm(forms.ModelForm):
    error_css_class = 'form-group has-error'

    class Meta:
        model = Case
        exclude = ['medinfo', 'last_action']
        widgets = {
            'status' : forms.Select(attrs={'class':'form-control '}),
            'diagnosis' : forms.TextInput(attrs={'class':'form-control '}),
            'test_result' : forms.TextInput(attrs={'class':'form-control '}),
            'problem' : forms.Textarea(attrs={'class':'form-control', 'rows':6}),
        }

class PrescriptionForm(forms.ModelForm):

    class Meta: 
        model = Prescription
        exclude = ['case']


class MedinfoViewForm(forms.ModelForm):

    class Meta:
        model = MedicalInformation

        

class EmergencyContactForm(forms.ModelForm):
    error_css_class = 'form-group has-error'

    class Meta:
        model = EmergencyContact
        exclude = ['patient']
        widgets = {
            'name' : forms.TextInput(attrs={'class':'form-control '}),
            'phone' : forms.TextInput(attrs={'class':'form-control'}),
            'relationship' : forms.TextInput(attrs={'class':'form-control'}),
        }


class InsuranceInformationForm(forms.ModelForm):
    error_css_class = 'form-group has-error'

    class Meta:
        model = InsuranceInformation
        exclude = ['patient']
        widgets = {
            'policy_holder' : forms.TextInput(attrs={'class':'form-control '}),
            'carrier' : forms.Select(attrs={'class':'form-control'}),
            'policy_number' : forms.TextInput(attrs={'class':'form-control'}),
        }

class AllergenForm(forms.ModelForm):
    error_css_class = 'form-group has-error'

    class Meta:
        model = Allergen
        exclude = ['medinfo']
        widgets = {
            'food_allegies' : forms.TextInput(attrs={'class':'form-control '}),
            'drug_allegies' : forms.Select(attrs={'class':'form-control'}),
            'environmental_allegies' : forms.TextInput(attrs={'class':'form-control'}),
        }

medicalinfo/templates/medicalinfo/medinfo_case_detail_view_form.html
{%extends 'base.html' %}

{% block content %}



<div class="container">

<div class="page-header">
        <h1>Case Detail <small>Patient: {{patient}}</small></h1>
 </div>

    <form action="" method="POST">{%csrf_token%}
      
    <div class="row">
    <div class="col-md-6">

        {{form1.as_p}}
    </div>
    <div class="col-md-6">
    	<h3>Prescription</h3>
        <div clsas="container">
            <table class="table table-hover">
                <thead>
                    <tr>
                        <th>Drug</th>
                        <th>Refill</th>
                        <th>Instruction</th>
                    </tr>
                </thead>
                <tbody>
{%for pres in prescriptions%}
                    <tr>
                        <th>{{pres.drug}}</th>
                        <th>{{pres.refill}}</th>
                        <th>{{pres.instruction}}</th>

                    </tr>

{%endfor%}
                </tbody>

            </table>
        </div>
    {%if user.employee.doctor %}
        <a class="btn btn-primary" href="{%url 'case-update-prescription' ref_id=ref_id case_id=case_id%}">New Precription</a>
        <a class="btn btn-default" href="{%url 'case-list-view' ref_id=ref_id %}">Back</a>
   

     {%endif%}
       
    </div>

    </div>

    {%if user.employee.doctor %}
    <a class="btn btn-primary" href="{%url 'case-update' ref_id=ref_id case_id=case_id%}">Update</a>
    <a class="btn btn-default" href="{%url 'case-list-view' ref_id=ref_id %}">Back</a>
   
    {%endif%}
    <a class="btn btn-default" href="{%url 'case-list-view' ref_id=ref_id%}">Back</a>

    </form>

<div class="containter"> 
<div id="content">
    <div class='hidden'>
        <h2>Case Report</h2>
        <h3> Patient: {{patient}}</h3>
        <p id="demo"></p>


            <table class="table">
                    <tr>
                        <th>Problem/Concern: {{case.problem}}</th>
                    </tr>
                    <tr>
                        <th>Diagnosis: {{case.diagnosis}}</th>
                    </tr>
                    <tr>
                        <th>Test Result: {{case.test_result}}</th>
                    </tr>
            </table>
                <h3>Prescription</h3>
                    <table class="table table-hover">
                <thead>
                    <tr>
                        <th>Drug</th>
                        <th>Refill</th>
                        <th>Instruction</th>
                    </tr>
                </thead>
                <tbody>
{%for pres in prescriptions%}
                    <tr>
                        <th>{{pres.drug}}</th>
                        <th>{{pres.refill}}</th>
                        <th>{{pres.instruction}}</th>

                    </tr>

{%endfor%}
                </tbody>

            </table>
        </div>

    </div>

</div> <hr>
<button class="btn btn-primary" id="cmd"><span class="glyphicon glyphicon-floppy-disk"></span> Save as PDF</button>
</form>

</div><!-- /container -->
<script>
document.getElementById("demo").innerHTML = Date();
</script>

{% endblock %}

medicalinfo/templates/medicalinfo/medinfo_case_list_view.html
{%extends 'base.html' %}

{% block content %}


<div class="container">
 <div class="page-header">
	<h1>Cases <small>Patient: {{patient}}</small></h1>

</div>



<nav>
<ul class="pagination">
    <span class="step-links">
        {% if cases.has_previous %}
            <a href="?page={{ cases.previous_page_number }}"><span class="glyphicon glyphicon-arrow-left"></a>
        {% endif %}

        <span class="current">
            Page {{ cases.number }} of {{ cases.paginator.num_pages }}.
        </span>

        {% if cases.has_next %}
            <a href="?page={{ cases.next_page_number }}"><span class="glyphicon glyphicon-arrow-right"></span></a>
        {% endif %}
    </span>
</ul>

</nav>


<table class="table">
<thead>
	<tr>
		<th>Case</th>
		<th>Status*</th>
		<th>Last Action</th>
	</tr>
</thead>
<tbody>
	{%for case in cases%}
	<tr>
		<th> <a href="{% url 'case-detail-view' ref_id=ref_id case_id=case.id %}"> {{case}}</a></th>
		<th>{{case.status}}</th>
		<th>{{case.get_last_action_display}} on {{case.updated}}</th>
	</tr>
{%endfor%}

</tbody>
</table>
    <a class="btn btn-primary" href="{%url 'case-init' ref_id=ref_id%}">New Case Inquiry</a>
    
<p class="help-block">*Case Status: N=New, A=Active, C=Closed</p>
</div>
{% endblock %}

medicalinfo/templates/medicalinfo/medinfo_case_update_form.html
{%extends 'base.html' %}

{% block content %}
<div class="container">

    <form action="" method="POST">{%csrf_token%}
      
    <div class="row">
    <div class="col-md-6">
    <h3>Case Detail</h3>

        {{form1.as_p}}
    </div>

    <div class="col-md-6">
    	<h3>Prescription</h3>
      <div clsas="container">
            <table class="table table-hover">
                <thead>
                    <tr>
                        <th>Drug</th>
                        <th>Refill</th>
                        <th>Instruction</th>
                    </tr>
                </thead>
                <tbody>
{%for pres in prescriptions%}
                    <tr>
                        <th>{{pres.drug}}</th>
                        <th>{{pres.refill}}</th>
                        <th>{{pres.instruction}}</th>

                    </tr>

{%endfor%}
                </tbody>

            </table>
        </div>

    </div>

    </div>

    {%if user.employee.doctor %}
    <button class="btn btn-primary" type="submit">Update</button>
    {%endif%}
 
    </form>

</div> <!-- /container -->


{% endblock %}

medicalinfo/templates/medicalinfo/medinfo_case_update_prescription_form.html
{%extends 'base.html' %}

{% block content %}
<div class="container">

    <form action="" method="POST">{%csrf_token%}
      
    <div class="row">
    <div class="col-md-6">
    <h3>Case Detail</h3>

        {{form1.as_p}}
    </div>

    <div class="col-md-6">
    	<h3>Prescription</h3>
      <div clsas="container">
            <table class="table table-hover">
                <thead>
                    <tr>
                        <th>Drug</th>
                        <th>Refill</th>
                        <th>Instruction</th>
                    </tr>
                </thead>
                <tbody>
{%for pres in prescriptions%}
                    <tr>
                        <th>{{pres.drug}}</th>
                        <th>{{pres.refill}}</th>
                        <th>{{pres.instruction}}</th>

                    </tr>

{%endfor%}
                </tbody>

            </table>
        </div>

        {{form2.as_p}}
    {%if user.employee.doctor %}
    <button class="btn btn-primary" type="submit">Update</button>
    {%endif%}
 

    </div>

    </div>

    </form>

</div> <!-- /container -->


{% endblock %}

medicalinfo/templates/medicalinfo/medinfo_diagnosis_init_form.html
{%extends 'base.html' %}

{% block content %}
<div class="container">

    <form action="" method="POST">{%csrf_token%}
      
    <h2>New Diagnosis</h2>
    <div class="row">
    <div class="col-md-6">
        {{form1.as_p}}
    </div>
    </div>


    <button class="btn btn-primary" type="submit">Submit</button>
 
    </form>

</div> <!-- /container -->


{% endblock %}

medicalinfo/templates/medicalinfo/medinfo_init_form.html
{%extends 'base.html' %}

{% block content %}
<div class="container">
<div class="page-header">
  <h1>Medical Information Initialization</small></small></h1>
</div>

    <form action="" method="POST">{%csrf_token%}
      
     <div class="row">
    <div class="col-md-6">
        <div class="col-md-8">
        {{form1.as_p}}
        </div>
    </div>
    </div>

    <div class="row"> 
    <div class="col-md-6">
        <h4>Emergency Contact</h4><hr>
        <div class="col-md-8">
        {{form3.as_p}}
        </div>    
    </div>
    <div class="col-md-6">
        <h4>Insurance Information</h4><hr>
        <div class="col-md-8">
        {{form4.as_p}}
        </div>
    </div>
    </div>


    <div class="row">
    <div class="col-md-6">
    <h4>Chronical Problem History</h4><hr>
    <table class="table">
        <tr>
            <td>
                {% for field in form2|slice:":4" %}
                <div class="text-right">
                {{ field.label_tag }} 
                {{ field }}
                </div>
                {%endfor%}
             </td>
            <td>
                {% for field in form2|slice:"4:" %}
                <div class="text-left">
                {{ field.label_tag }} 
                {{ field }}
                </div>
                {%endfor%}
             </td>
        </tr>
    </table>
     </div>

     <div class="col-md-6">
     <h4>Allergens</h4><hr>
        <div class="col-md-8">
        {{form5.as_p}}
        </div>

     </div>


     </div>
    <button class="btn btn-primary" type="submit">Submit</button>
 
    </form>

    </div> <!-- /container -->


{% endblock %}

medicalinfo/templates/medicalinfo/medinfo_new_case_form.html
{%extends 'base.html' %}

{% block content %}
<div class="container">

    <form action="" method="POST">{%csrf_token%}
      <div class="page-header">
        <h1>New Case Inquiry</h1>
       </div>

    <div class="row">
    <div class="col-md-6">
        {{form1.as_p}}
    </div>
    </div>


    <button class="btn btn-primary" type="submit">Submit</button>
 	<a class="btn btn-default" href="{%url 'case-list-view' ref_id=ref_id%}">Back</a>
    </form>

</div> <!-- /container -->


{% endblock %}

medicalinfo/templates/medicalinfo/medinfo_view_form.html
{%extends 'base.html' %}

{% block content %}
        <div class="container">

      <form action="" method="POST">{%csrf_token%}
      <div class="page-header">
        <h1>Medical Information</h1>
        </div>

    <div class="row">
    <div class="col-md-6">
        {{form1.as_p}}
    </div>
    <div class="col-md-6">
    <a class="btn btn-primary" href="{%url 'case-list-view' ref_id=ref_id%}">View Cases</a>
    <a class="btn btn-primary" href="{%url 'case-init' ref_id=ref_id%}">New Case Inquiry</a>
 {%if user.patient.is_active %}
<br>    
<br> 
 <a class="btn btn-default" href="{{user.patient.get_write_to_doc_url}}"><span class="glyphicon glyphicon-envelope" aria-hidden="true"></span> Doctor</a>
 <a class="btn btn-default" href="{{user.patient.get_write_to_nurse_url}}"><span class="glyphicon glyphicon-envelope" aria-hidden="true"></span> Nurse</a>

 {%endif%}


    </div>
    </div>

    <div class="row">
    <div class="col-md-6">
        <h4>Emergency Contact</h4><hr>
        {{form3.as_p}}
    </div>
    <div class="col-md-6">
        <h4>Insurance</h4><hr>
        {{form4.as_p}}
    </div>
    </div>


    <div class="row">
    <div class="col-md-6">
    <h4>Chronical Problem History</h4><hr>
    <table class="table">
        <tr>
            <td>
                {% for field in form2|slice:":4" %}
                <div class="text-right">
                {{ field.label_tag }} 
                {{ field }}
                </div>
                {%endfor%}
             </td>
            <td>
                {% for field in form2|slice:"4:" %}
                <div class="text-left">
                {{ field.label_tag }} 
                {{ field }}
                </div>
                {%endfor%}
             </td>
        </tr>
    </table>
     </div>

     <div class="col-md-6">
     <h4>Allergens</h4><hr>
     {{form5.as_p}}
     </div>
     </div>
         <button class="btn btn-primary" type="submit">Update</button>
 
</form>

    </div> <!-- /container -->


{% endblock %}